---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-6beb89bfe4a6e0414a54f972bcb5b77b
  name: nginxpriv
  namespace: wego-system
spec:
  branch: main
  config_url: ssh://git@github.com/J-Thompson12/gitops-app-config.git
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/J-Thompson12/nginxpriv.git
